from selenium import webdriver
import time
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
chrome_options = webdriver.ChromeOptions()
chrome_options.add_experimental_option("detach", True)

driver = webdriver.Chrome(options=chrome_options)
driver.get("https://www.linkedin.com/jobs/search/?currentJobId=4226517770&distance=25&f_AL=true&geoId=103644278&keywords=Presentation%20Specialist&origin=JOB_SEARCH_PAGE_KEYWORD_HISTORY&refresh=true")
time.sleep(2)
sign_in_button = driver.find_element(By.XPATH, value='//*[@id="base-contextual-sign-in-modal"]/div/section/div/div/div/div[2]/button')
sign_in_button.send_keys(Keys.ENTER)
email = driver.find_element(By.XPATH, value='//*[@id="base-sign-in-modal_session_key"]')
email.click()
email.send_keys("example@gmail.com")
password = driver.find_element(By.XPATH, value='//*[@id="base-sign-in-modal_session_password"]')
password.click()
password.send_keys("Psss")
login = driver.find_element(By.XPATH, value='//*[@id="base-sign-in-modal"]/div/section/div/div/form/div[2]/button')
login.click()
time.sleep(2)
easy_apply = driver.find_element(By.ID, value="jobs-apply-button-id")
easy_apply.click()
time.sleep(2)
next_button = driver.find_element(By.CLASS_NAME, value='ph5 button')
next_button.click()
time.sleep(2)
next_button.click()
time.sleep(2)
experience_level = driver.find_element(By.XPATH, value='//*[@id="single-line-text-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-4226517770-19386775156-numeric"]')
experience_level.click()
experience_level.send_keys("5")
review_button = driver.find_element(By.CLASS_NAME, value='ph5 button')
review_button.click()
driver.quit()